AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  corebizfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::695909514658:role/service-role/corebiz-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/items/{id}'
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /items
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: '/itemsDELETE/{id}'
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /items
            Method: ANY
